version: 1
project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: dist/wekan.lpk
update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: wekan
build:
  run_buildscript: false
images:
  - id: wekan
    target: service
    service: wekan
    source: ghcr.io/wekan/wekan
    channel: custom
    tag_regex: '^v?[0-9]+\.[0-9]{2}$'
    sort: semver
    version_regex: '^v?(?P<version>[0-9]+)\.(?P<minor>[0-9])(?P<patch>[0-9])$'
    version_template: '{version}.{minor}.{patch}'
    delivery:
      mode: lazycat
  - id: mongo
    target: service
    service: wekandb
    source: mongo
    channel: custom
    tag_regex: '^7$'
    sort: created
    delivery:
      mode: lazycat
stores:
  official:
    enabled: true
    skip_if_version_exists: true
  private:
    enabled: true
    skip_if_version_exists: true
    name: WeKan
    summary: 开源、可自托管的协作看板应用

