package: cloud.lazycat.app.wekan
version: 9.9.9
name: WeKan
description: "开源看板应用"
min_os_version: 1.5.0
homepage: https://github.com/wekan/wekan
author: wekan
locales:
  zh:
    name: "WeKan"
    description: "开源、可自托管的协作看板应用"
  en:
    name: "WeKan"
    description: "An open-source, self-hosted collaborative kanban application"
